name: "Assign Asana Task on PR Review Request"
description: "Assigns an existing Asana task to a user based on PR review request"
author: "Taimur Salman"
inputs:
  token:
    description: "Asana Personal Access Token"
    required: true
  pr-url:
    description: "Pull Request URL"
    required: true
  project-id:
    description: "Asana project GID"
    required: true
  assignee-email:
    description: "Email of person to assign task to"
    required: false
  reviewer-login:
    description: "Reviewer username"
    required: false
  branch-name:
    description: "Name of current branch (Used for searching commits to find reviewer email"
    required: false
  task-id:
    description: "The asana task ID to be updated. If not passed, then uses the pr-url to get the asana task id"
    required: false

outputs:
  assigned:
    description: "Whether the task was successfully assigned"
  assignee:
    description: "Name of the assigned user"

runs:
  using: "node20"
  main: "code/build/index.js"
